FROM debian:oldstable

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    nginx \
    openssl \
    curl \
    iproute2

COPY ./conf/site.conf /default.conf
COPY ./tools/script.sh /

RUN chmod 777 /script.sh

CMD ["/script.sh"]