# Minimal Redis configuration for Docker
bind 0.0.0.0
#requirepass mypassword
protected-mode no
port 6379
maxmemory 256mb
maxmemory-policy allkeys-lru
daemonize no
save 900 1
save 300 10
save 60 10000
loglevel notice
logfile ""


# Enable AOF persistence
appendonly yes
