server.document-root = "/var/www/html"
server.port = 8080
server.bind = "0.0.0.0"

index-file.names = ("index.html")
dir-listing.activate = "disable"

setenv.add-response-header = ( "Content-Type" => "text/html; charset=utf-8" )

accesslog.filename = "/var/log/lighttpd/access.log"
server.errorlog = "/var/log/lighttpd/error.log"